apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: b
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: b
    spec:
      containers:
      - name: b
        image: abcd:latest
        args: [b]
        ports:
          - containerPort: 8080
            name: rest
            protocol: TCP
        env:
          - name: c_uri
            valueFrom: 
              configMapKeyRef:
                name: all-config
                key: c.uri
