apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: d
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: d
    spec:
      containers:
      - name: d
        image: abcd:latest
        args: [d]
        ports:
          - containerPort: 8080
            name: rest
            protocol: TCP
